site_name: C4
theme: readthedocs
nav:
  - Home: index.md
  - Overview: overview.md
  - Examples:
    - Go: examples/go.md
    - .NET: examples/net-core.md
    - NodeJS: examples/nodejs.md
    - Python: examples/python.md
    - Rust: examples/rust.md
  - Plugins:
    - AWS S3:
      - Overview: plugins/aws-s3/overview.md
      - Setup: plugins/aws-s3/setup.md
      - Usage: plugins/aws-s3/usage.md
    - GitHub Gist:
      - Overview: plugins/gist/overview.md