# .github/workflows/release.yml
name: Build and Release Extism Plugins

on:
  push:
    tags:
      - 'v*.*.*' 

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasip1

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build Gist plugin
      run: |
        cd plugins/gist
        cargo build --release --target wasm32-wasip1
        cp target/wasm32-wasip1/release/*.wasm ../../gist.wasm

    - name: Build AWS S3 plugin
      run: |
        cd plugins/aws-s3
        cargo build --release --target wasm32-wasip1
        cp target/wasm32-wasip1/release/*.wasm ../../aws-s3.wasm

    - name: Verify builds
      run: |
        ls -la *.wasm
        file gist.wasm
        file aws-s3.wasm

    - name: Create Release
      run: |
        gh release create ${{ steps.extract_version.outputs.VERSION }} \
          --title "Release ${{ steps.extract_version.outputs.VERSION }}" \
          --notes "" \
          gist.wasm \
          aws-s3.wasm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}